create table account (value float(53), id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table client_account (account_id bigint not null unique, client_id bigint not null);
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
alter table if exists client_account add constraint FKnx6ay9tbvt0nt9c5m3uw4um4y foreign key (account_id) references account;
alter table if exists client_account add constraint FKh7w5b6kuwp7qpf536nsetgxcs foreign key (client_id) references client;
create table account (value float(53), id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table client_account (account_id bigint not null unique, client_id bigint not null);
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
alter table if exists client_account add constraint FKnx6ay9tbvt0nt9c5m3uw4um4y foreign key (account_id) references account;
alter table if exists client_account add constraint FKh7w5b6kuwp7qpf536nsetgxcs foreign key (client_id) references client;
create table account (value float(53), id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table client_account (account_id bigint not null unique, client_id bigint not null);
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
alter table if exists client_account add constraint FKnx6ay9tbvt0nt9c5m3uw4um4y foreign key (account_id) references account;
alter table if exists client_account add constraint FKh7w5b6kuwp7qpf536nsetgxcs foreign key (client_id) references client;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table client_account (account_id bigint not null unique, client_id bigint not null);
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
alter table if exists client_account add constraint FKnx6ay9tbvt0nt9c5m3uw4um4y foreign key (account_id) references account;
alter table if exists client_account add constraint FKh7w5b6kuwp7qpf536nsetgxcs foreign key (client_id) references client;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), id bigint not null, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
create sequence test_seq start with 1 increment by 50;
create table test (id bigint not null, primary key (id));
create sequence test_seq start with 1 increment by 50;
create table test (id bigint not null, primary key (id));
create sequence test_seq start with 1 increment by 50;
create table test (id bigint not null, primary key (id));
create sequence account_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence currency_seq start with 1 increment by 50;
create sequence transaction_seq start with 1 increment by 50;
create table account (value float(53), client_id bigint not null, id bigint not null, currency_iso varchar(255) unique, primary key (id));
create table client (id bigint not null, primary key (id));
create table currency (iso varchar(255) not null, name varchar(255), primary key (iso));
create table transaction (id bigint not null, primary key (id));
alter table if exists account add constraint FKkm8yb63h4ownvnlrbwnadntyn foreign key (client_id) references client;
alter table if exists account add constraint FKl7ohq3on8ug9kjh1u662suvr5 foreign key (currency_iso) references currency;
